"use client";

import { Mic, SendHorizonal, Upload, Loader2 } from "lucide-react";
import { useState, useRef } from "react";
import { cn } from "@/lib/utils";
import { Textarea } from "@/components/ui/textarea";
import { useAutoResizeTextarea } from "@/hooks/use-auto-resize-textarea";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Button } from "@/components/ui/button";
import { AIVoiceInput } from "@/components/ui/ai-voice-input";

interface RuixenQueryBoxProps {
  onSend: (message: string, isAudio?: boolean) => void;
  isLoading?: boolean;
}

export default function RuixenQueryBox({ onSend, isLoading }: RuixenQueryBoxProps) {
  const { textareaRef, adjustHeight } = useAutoResizeTextarea({
    minHeight: 56,
    maxHeight: 220,
  });

  const [inputValue, setInputValue] = useState("");
  const [isRecording, setIsRecording] = useState(false);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  // Ref to track if the current input was generated by voice
  const isVoiceInputRef = useRef(false);

  const handleSend = () => {
    if (!inputValue.trim() || isLoading) return;
    onSend(inputValue, isVoiceInputRef.current);
    setInputValue("");
    isVoiceInputRef.current = false;
    adjustHeight(true);
  };

  const handleFileUpload = (files: FileList | null) => {
    if (!files) return;
    console.log("Uploaded files:", files);
  };

  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);

  const toggleRecording = async () => {
    if (isRecording) {
      if (mediaRecorderRef.current) {
        mediaRecorderRef.current.stop();
      }
      return;
    }

    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mediaRecorder = new MediaRecorder(stream);
      mediaRecorderRef.current = mediaRecorder;
      audioChunksRef.current = [];

      mediaRecorder.ondataavailable = (event) => {
        if (event.data.size > 0) {
          audioChunksRef.current.push(event.data);
        }
      };

      mediaRecorder.onstart = () => {
        setIsRecording(true);
        // Play silent audio to unlock AudioContext for TTS autoplay
        const silentAudio = new Audio("data:audio/wav;base64,UklGRigAAABXQVZFZm10IBIAAAABAAEARKwAAIhYAQACABAAAABkYXRhAgAAAAEA");
        silentAudio.play().catch(() => {});

        // Voice Activity Detection (Auto-stop on silence)
        try {
          const AudioContext = window.AudioContext || (window as any).webkitAudioContext;
          if (AudioContext) {
            const audioContext = new AudioContext();
            const analyser = audioContext.createAnalyser();
            const source = audioContext.createMediaStreamSource(stream);
            source.connect(analyser);
            analyser.fftSize = 512;
            const bufferLength = analyser.frequencyBinCount;
            const dataArray = new Uint8Array(bufferLength);
            
            let silenceStart = Date.now();
            let hasSpoken = false;

            const checkSilence = () => {
              if (mediaRecorder.state !== "recording") {
                audioContext.close().catch(() => {});
                return;
              }
              
              analyser.getByteFrequencyData(dataArray);
              const sum = dataArray.reduce((a, b) => a + b, 0);
              const average = sum / bufferLength;
              
              if (average > 12) { // Volume threshold
                silenceStart = Date.now();
                hasSpoken = true;
              } else {
                // If they spoke and then went silent for 1.8 seconds, auto-stop
                if (hasSpoken && Date.now() - silenceStart > 1800) {
                  mediaRecorder.stop();
                  return;
                }
              }
              requestAnimationFrame(checkSilence);
            };
            checkSilence();
          }
        } catch (e) {
          console.warn("Silence detection failed to start:", e);
        }
      };

      mediaRecorder.onstop = async () => {
        setIsRecording(false);
        stream.getTracks().forEach((track) => track.stop());

        const audioBlob = new Blob(audioChunksRef.current, { type: "audio/webm" });
        audioChunksRef.current = [];

        if (audioBlob.size === 0) return;

        // Visual indicator that we are processing
        setInputValue("Listening to you...");

        const reader = new FileReader();
        reader.readAsDataURL(audioBlob);
        reader.onloadend = async () => {
          const base64data = (reader.result as string).split(",")[1];
          try {
            const res = await fetch(`${import.meta.env.VITE_API_URL || ""}/api/stt`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ audioBase64: base64data }),
            });
            const data = await res.json();
            if (data.text && data.text.trim()) {
              setInputValue(data.text);
              isVoiceInputRef.current = true;
              
              // Google Assistant style: Auto-send the transcribed voice!
              setTimeout(() => {
                onSend(data.text, true);
                setInputValue("");
              }, 600);
            } else {
              setInputValue("");
            }
          } catch (e) {
            console.error(e);
            setInputValue("");
            alert("Failed to transcribe audio.");
          }
        };
      };

      mediaRecorder.start();
    } catch (err) {
      console.error("Microphone access denied:", err);
      alert("Microphone access is required for voice input.");
    }
  };

  return (
    <div className="w-full py-6">
      <div
        className="relative max-w-2xl bg-white rounded-2xl border border-gray-300 shadow-sm overflow-hidden"
        style={{
          backgroundImage:
            "url('https://pub-940ccf6255b54fa799a9b01050e6c227.r2.dev/ruixen_chat_gradient.png')",
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        <Textarea
          id="ai-textarea"
          ref={textareaRef}
          disabled={isLoading}
          placeholder={isLoading ? "Thinking..." : isRecording ? "Listening..." : "Ask anything..."}
          className={cn(
            "w-full resize-none border-none bg-transparent",
            "text-base text-white placeholder:text-gray-400",
            "px-5 py-4 pr-24 rounded-2xl leading-[1.4]",
            "transition-all focus-visible:ring-0 focus-visible:ring-offset-0"
          )}
          value={inputValue}
          onChange={(e) => {
            setInputValue(e.target.value);
            adjustHeight();
          }}
          onKeyDown={(e) => {
            if (e.key === "Enter" && !e.shiftKey) {
              e.preventDefault();
              handleSend();
            }
          }}
        />

        {/* Icon Buttons */}
        <div className="absolute bottom-3 right-3 flex items-center gap-2">
          <AIVoiceInput 
            onStart={toggleRecording} 
            onStop={() => toggleRecording()} 
          />
          {/* File Upload Popover */}
          <Popover>
            <PopoverTrigger asChild>
              <button
                type="button"
                className="p-2 rounded-full bg-gray-200 hover:bg-gray-300 text-gray-600 transition-colors"
              >
                <Upload className="w-4 h-4" />
              </button>
            </PopoverTrigger>
            <PopoverContent className="w-60 p-4">
              <p className="text-sm mb-2 text-slate-800">Upload files:</p>
              <input
                type="file"
                multiple
                ref={fileInputRef}
                onChange={(e) => handleFileUpload(e.target.files)}
                className="w-full border border-gray-300 rounded p-1 text-slate-800"
              />
              <Button
                className="mt-2 w-full"
                onClick={() => fileInputRef.current?.click()}
              >
                Choose Files
              </Button>
            </PopoverContent>
          </Popover>

          <button
            type="button"
            onClick={handleSend}
            disabled={!inputValue.trim()}
            className={cn(
              "p-2 rounded-full transition-colors",
              inputValue.trim()
                ? "bg-[#004a58] text-white"
                : "bg-gray-200 text-gray-400 cursor-not-allowed"
            )}
          >
            <SendHorizonal className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
}
